// Check the swagger config generation
GET {{ base_uri }}/v2/api-docs HTTP/1.1
Accept: application/json

> {%
client.test("Request executed successfully", function() {

  client.assert(
      response.status === 200,
      "Response status is not 200");

  client.assert(
      response.contentType.mimeType === "application/json",
      "Unexpected content type - MIME type");

  client.assert(
      response.body.hasOwnProperty("swagger"),
      "Expected body to contain 'swagger'");

});
%}
