### PUT a non-existing user should fail
PUT {{ base_uri }}/api/users/1 HTTP/1.1
Content-Type: application/json

{
  "age": 23,
  "name": "Pierre",
  "firstname": "Bouillon"
}

> {%
client.test("Request successfully failed", function() {

  client.assert(
      response.status === 404,
      "Response status is not 404");

});
%}
