### PUT a non-existing user should fail
PUT {{ base_uri }}/api/users/{{nonexistent-user-id}} HTTP/1.1
Content-Type: application/json

{
  "age": 23,
  "name": "Bouillon",
  "firstname": "Pierre"
}

> {%
client.test("Request successfully failed", function() {

  client.assert(
      response.status === 404,
      "Response status is not 404");

});
%}

### Create the user and store its id
POST {{ base_uri }}/api/users/ HTTP/1.1
Content-Type: application/json

{
  "age": 24,
  "name": "Bouillon",
  "firstname": "Pierre"
}

> {% client.global.set("id", response.body.json.id); %}

### PATCH on the created user should work
PUT {{ base_uri }}/api/users/{{id}} HTTP/1.1
Content-Type: application/json

{
  "age": 23,
  "name": "Bouillon",
  "firstname": "Pierre"
}
